Changes to back up to ubuntu hardy, debhelper 5

diff --git a/DiskUsage/debian/rules b/DiskUsage/debian/rules
--- a/DiskUsage/debian/rules
+++ b/DiskUsage/debian/rules
@@ -1,67 +1,155 @@
 #!/usr/bin/make -f
+# This debian/rules file is provided as a template for normal perl
+# packages. It was created by Marc Brockschmidt <marc@dch-faq.de> for
+# the Debian Perl Group (http://pkg-perl.alioth.debian.org/) but may
+# be used freely wherever it is useful.
+#
+# It was later modified by Jason Kohles <email@jasonkohles.com>
+# http://www.jasonkohles.com/ to support Module::Build installed modules
 
-DOCROOT = /var/www/domains/gsc.wustl.edu/gscweb
+# Uncomment this to turn on verbose mode.
+#export DH_VERBOSE=1
 
-HTML = ./html/diskusage.html
+# If set to a true value then MakeMaker's prompt function will
+# always return the default without waiting for user input.
+export PERL_MM_USE_DEFAULT=1
+
+PACKAGE=$(shell dh_listpackages)
+
+ifndef PERL
+PERL = /usr/bin/perl
+endif
+
+TMP     =$(CURDIR)/debian/$(PACKAGE)
+
+DOCROOT = /var/www/domains/gsc.wustl.edu/diskusage/htdocs
+
+CGIROOT= /var/www/domains/gsc.wustl.edu/diskusage
+
+CONFIG = etc/diskusage.gsc.wustl.edu.conf \
+etc/diskusage-inc.gsc.wustl.edu.conf
+
+HTML = ./htdocs/diskusage.html \
+./htdocs/favicon.ico
 
 SCRIPT = ./bin/disk_usage.pl
 
-JS = ./media/js/jquery.js \
-./media/js/jquery.dataTables.js \
-./media/js/jquery.dataTables.min.js.gz \
-./media/js/jquery.dataTables.min.js
+JS = media/js/jquery.js \
+media/js/jquery.dataTables.js \
+media/js/jquery.dataTables.min.js.gz \
+media/js/jquery.dataTables.min.js
 
-CSS = ./media/css/diskusage_table.css \
-./media/css/diskusage_page.css
+CSS = media/css/diskusage_table.css \
+media/css/diskusage_page.css
 
-IMAGES = ./media/images/forward_enabled.jpg \
-./media/images/back_enabled.jpg \
-./media/images/back_disabled.jpg \
-./media/images/sort_both.png \
-./media/images/forward_disabled.jpg \
-./media/images/sort_asc.png \
-./media/images/sort_desc.png \
-./media/images/sort_both.png
+IMAGES = media/images/forward_enabled.jpg \
+media/images/back_enabled.jpg \
+media/images/back_disabled.jpg \
+media/images/sort_both.png \
+media/images/forward_disabled.jpg \
+media/images/sort_asc.png \
+media/images/sort_desc.png \
+media/images/sort_both.png
 
-PERLMODS = ./lib/DiskUsage.pm \
-./lib/DiskUsage/SNMP.pm \
-./lib/DiskUsage/Cache.pm \
-./lib/DiskUsage/Error.pm
+PERLMODS = lib/DiskUsage.pm \
+lib/DiskUsage/SNMP.pm \
+lib/DiskUsage/Cache.pm \
+lib/DiskUsage/Error.pm
 
-CGI = ./cgi-bin/du.config \
-./cgi-bin/du_summarytable.cgi \
-./cgi-bin/du_total.cgi \
-./cgi-bin/du_hosttable.cgi \
-./cgi-bin/du_volumetable.cgi
+CGI = cgi-bin/du.config \
+cgi-bin/du_summarytable.cgi \
+cgi-bin/du_total.cgi \
+cgi-bin/du_hosttable.cgi \
+cgi-bin/du_volumetable.cgi
 
+.PHONY: images
 images: $(IMAGES)
 	for ITEM in $(IMAGES); do \
-		install -D -m 0644 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/media/images/$${ITEM} ; \
+		install -D -m 0644 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/$${ITEM} ; \
 	done
 
+.PHONY: css
 css: $(CSS)
 	for ITEM in $(CSS); do \
-		install -D -m 0644 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/media/css/$${ITEM} ; \
+		install -D -m 0644 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/$${ITEM} ; \
 	done
 
+.PHONY: js
 js: $(JS)
 	for ITEM in $(JS); do \
-		install -D -m 0644 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/media/js/$${ITEM} ; \
+		install -D -m 0644 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/$${ITEM} ; \
 	done
 
+.PHONY: cgi
 cgi: $(CGI)
 	for ITEM in $(CGI); do \
-		install -D -m 0755 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/cgi-bin/$${ITEM} ; \
+		install -D -m 0755 $${ITEM} $(CURDIR)/debian/libdiskusage-perl/$(CGIROOT)/$${ITEM} ; \
 	done
 
-html: $(HTML)
-	install -D -m 0644 $(HTML) $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/diskusage.html
+.PHONY: htdocs
+htdocs: $(HTML)
+	install -D -m 0644 htdocs/diskusage.html $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/diskusage.html
+	install -D -m 0644 htdocs/favicon.ico $(CURDIR)/debian/libdiskusage-perl/$(DOCROOT)/favicon.ico
 
-#du_install: html cgi js css images
+.PHONY: config
+config: $(CONFIG)
+	install -d $(CURDIR)/debian/libdiskusage-perl/etc/apache2/sites-enabled/includes
+	install -D -m 0644 ./etc/diskusage-inc.gsc.wustl.edu.conf $(CURDIR)/debian/libdiskusage-perl/etc/apache2/sites-available/includes/diskusage.gsc.wustl.edu.conf
+	install -D -m 0644 ./etc/diskusage.gsc.wustl.edu.conf $(CURDIR)/debian/libdiskusage-perl/etc/apache2/sites-available/diskusage.gsc.wustl.edu.conf
+	ln -s ../sites-available/diskusage.gsc.wustl.edu.conf $(CURDIR)/debian/libdiskusage-perl/etc/apache2/sites-enabled/diskusage.gsc.wustl.edu.conf
 
-override_dh_install: html cgi js css images
-	dh_install --
+local_install: config htdocs cgi js css images
 
-%:
-	dh_$@
+build: build-stamp
+build-stamp:
+	dh_testdir
+
+	# Add commands to compile the package here
+	$(PERL) Build.PL installdirs=vendor
+	$(PERL) Build
+#	$(PERL) Build test
+
+	touch $@
+
+clean:
+	dh_testdir
+	dh_testroot
+	dh_clean build-stamp install-stamp
+
+	# Add commands to clean up after the build process here
+	[ ! -f Build ] || $(PERL) Build distclean
+
+install: install-stamp
+install-stamp: build-stamp
+	dh_testdir
+	dh_testroot
+	dh_clean -k
+
+	# Add commands to install the package into debian/$PACKAGE_NAME here
+	$(PERL) Build install destdir=$(TMP) create_packlist=0
+
+	touch $@
+
+binary-arch:
+# We have nothing to do here for an architecture-independent package
+
+binary-indep: build install local_install
+	dh_testdir
+	dh_testroot
+	dh_installdocs 
+	dh_installexamples
+	dh_installchangelogs debian/changelog
+	dh_perl
+	dh_compress
+	dh_fixperms
+	dh_installdeb
+	dh_gencontrol
+	dh_md5sums
+	dh_builddeb
+
+source diff:
+	@echo >&2 'source and diff are obsolete - use dpkg-source -b'; false
+
+binary: binary-indep binary-arch
+.PHONY: build clean binary-indep binary-arch binary
 
